{
  "WorkItem": {
    "AffectedComponent": {
      "Name": "",
      "DisplayName": ""
    },
    "ClosedComment": "Fixed in 0.9 branch",
    "ClosedDate": "2013-04-02T15:51:17.42-07:00",
    "CommentCount": 1,
    "Custom": null,
    "Description": "Hi, this bug is related to the already [closed item 450](http://typescript.codeplex.com/workitem/450): \r\n\r\nHere is the repro:\r\n```\r\nmodule fred {\r\n\r\n\texport class Foo{ \r\n\t\tpublic name: string;\r\n\t\t}\r\n\r\n   export class Bar {\r\n\r\n        constructor(\r\n           public foo: Foo\r\n           ) {\r\n        }\r\n    }\r\n}\r\n\r\nvar cc = new fred.Bar({}); // ok: Error: Supplied parameters yada yada\r\n\r\n[].forEach( () => {\r\n\t\r\n\tvar one = abc; // Not ok: No error\t\r\n\tvar two = new fred.Bar({}); // Not ok: No error; also errors in var declarations above this line ignored \r\n\tvar three = abc; // ok: Error: The name 'abc' blah blah\r\n\r\n});\r\n```\r\n\r\nThere is a twist to this: If we remove the \"var two=...\" statement then the \"var one = abc\" error gets picked up.",
    "LastUpdatedDate": "2014-01-10T10:34:33.287-08:00",
    "PlannedForRelease": "",
    "ReleaseVisibleToPublic": false,
    "Priority": {
      "Name": "Low",
      "Severity": 50,
      "Id": 1
    },
    "ProjectName": "typescript",
    "ReportedDate": "2013-01-25T10:20:12.04-08:00",
    "Status": {
      "Name": "Closed",
      "Id": 4
    },
    "ReasonClosed": {
      "Name": "Unassigned"
    },
    "Summary": "Nested function bug back from the dead",
    "Type": {
      "Name": "Issue",
      "Id": 3
    },
    "VoteCount": 2,
    "Id": 651
  },
  "FileAttachments": [],
  "Comments": [
    {
      "Message": "Marking active",
      "PostedDate": "2013-01-28T11:04:13.687-08:00",
      "Id": 87531
    }
  ]
}